### ISSUE TITLE
How to Log into PostgreSQL?

### ISSUE THREAD

**Issue by nioperas06** [shipping-docker/vessel#104]
## Description
How to Log into PostgreSQL?

## OS

My OS is:

- [x] MacOS [**Choose one:** Yosemite, El Capitan, Sierra, High Sierra, Mojave]
- [ ] Linux
- [ ] Windows

## Docker

The output of `docker version`: 

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

The output of `docker-compose version`:

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Comment by fideloper** [comment]
Hi!

Vessel doesn't come with postgresql, just MySQL. 

However, if you [customized it to use pgsql](https://vessel.shippingdocker.com/docs/customizing-vessel/#pgsql), then you should do a quick review of official pgsql image page: https://hub.docker.com/_/postgres

It'll be something like `./vessel exec pgsql pgsql` (altho you might need to specify the username like`./vessel exec pgsql pgsql -U postgres`

**Comment by nioperas06** [comment]
Hi @fideloper 😃
Thanks for the reply!
When I run:
```
./vessel exec pgsql pgsql -U postgres
```
I have this error:
```
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"pgsql\": executable file not found in $PATH": unknown
```
So, to log into PostgreSQL:
```
docker exec -it postgres_container_name bash
root@xxxx:/# psql -U postgres
psql (10.0)
Type "help" for help.

postgres=# 
```
I'm still looking to find a way to log in from `vessel` and activate `PostgreSQL Extensions` 🙌

**Comment by fideloper** [comment]
Oh I gave you the command `pgsql` but the command is `psql`:

```bash
./vessel exec pgsql psql -U postgres
```

That's the same/equivalent as your `docker exec` command. You can use `bash` instead of `psql` of course.

Note: Enabling extensions may not work like you think. Any changes you make while docker is running likely won't be saved after you turn the containers off and back on.

Their docs mention extensions and suggest that you'll need to extend/create a `Dockerfile` to do so. Here's an example they link to that enables `postgis`: https://github.com/appropriate/docker-postgis/blob/f6d28e4a1871b1f72e1c893ff103f10b6d7cb6e1/10-2.4/Dockerfile

If you're not familiar with that, then I suggest learning a bit more about how Docker works. (check out https://serversforhackers.com/s/docker-in-dev-v2-i and https://serversforhackers.com/s/docker-in-dev-v2-ii)

**Comment by nioperas06** [comment]
I'll take that courses 🙇
