### ISSUE TITLE
Questions about Vessel Architecture

### ISSUE THREAD

**Issue by dbpolito** [shipping-docker/vessel#11]
Congratulations for Vessel, great project. ❤️ 

I do like Docker a lot, and i would like to discuss / ask some architectural choices you made on Vessel, if you don't care to answer.

1. Why having nginx and php on same machine? Just for simplifying things?
2. Why are you using supervisor on `app` service, why not just use docker `CMD`?
3. Why installing everything manually on raw ubuntu machine, instead of using docker oficial images?
4. Any experience with alpine images?

I did this version https://github.com/firework/FireDocker inspired on your docker series (which i liked a lot, congrats for that too), in case you want to see a slightly different approach.

**Comment by fideloper** [comment]
Hi!

Sure, happy to - 

1. Nginx and PHP on the same machine is just simpler. Note that Nginx (in it's standard setup) needs to be able to see the PHP file, otherwise it will return a 404 (this is a bit special to PHP apps). This isn't strictly necessary, but the most common Nginx setup seen and understand by the community does have this restriction. Having Nginx and PHP-FPM on the same container makes that setup more simple to understand.
    * It's possible to put them in separate containers successfully, but I just prefer not to
2. Supervisord is used because it's needed (or at least some solution is needed) to run more than one process in a container at the same time. Here we're running both Nginx and PHP-FPM, and so need something to do that.
3. This is using the docker official image of Ubuntu, however if you're asking why I didn't use the official PHP images, it's because:
    * The official PHP images are harder to work with
    * Ubuntu is more widely understood by those who may want to contribute

Yep, definitely familiar with Alpine (although I've only personally used it and built off of Alpine images once before)
