### ISSUE TITLE
Sqlite support?

### ISSUE THREAD

**Issue by madsem** [shipping-docker/vessel#132]
Sorry if this is a silly question, but is it possible to use a simple sqlite db in the app container instead of mysql? Or is there anything in vessel that would prevent this / expects the db container to be used?

**Comment by fideloper** [comment]
Hi!

Sqlite should “just work” (I use it in most projects with vessel for tests).

You may need to create an empty file for the database since I don’t believe
Laravel/SQLite creates one for you:

touch database/my_db.sql

(and then define “my_db.sql as the database in the sqlite connection
settings).

**Comment by madsem** [comment]
Great! Thanks a lot for replying so quick even during the holidays :)
Have a great time with family and a great new year!

**Comment by fideloper** [comment]
You too!
