### ISSUE TITLE
Publish application logs to docker

### ISSUE THREAD

**Issue by jake-harris** [shipping-docker/vessel#133]
## Description

Thank you for the excellent tool.

Is there an easy way to publish application logs to stdout as well as the nginx `access_log`? In other words I'd like the contents of laravel's log to output with docker's logs. Hope that makes sense.

## OS

My OS is:

- [ X ] MacOS [Mojave]
- [ ] Linux
- [ ] Windows

## Docker

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

The output of `docker-compose version`:

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Comment by fideloper** [comment]
There is not an easy way, which is a result of how PHP (and Laravel) works.

Docker logs are taken from the stdout/stderr of whatever process the Container is running. The app container  is running supervisord, which redirects stdout/stderr or php-fpm and nginx to supervisords stdout/stderr (which in turn docker spits out to docker logs).

Laravel (and php in general) application logs are NOT piped through php-fpm - they are separately written out to a file (or whatever  log configuration is used in your laravel application).

So there's a disconnect ("air gap" you might call it) between the processes that the Docker container/supervisord are monitoring/getting log out put from, and how PHP app logs are working.

That all being said, I don't know what happens if Laravel's log driver uses a stdout driver. Or perhaps there's a way to get app logs into php-fpm logs that I don't know about! (or there could be other ways to interact with docker logs that I'm unfamiliar with).

But....none of that is straightforward, so I don't think this will necessarily work within Vessel.

Hope that makes sense!!

**Comment by jake-harris** [comment]
That's more or less the answer I expected but not the one I wanted... I'll share any hacks I'm able to come up with here. Thanks for the quick answer!

**Comment by fideloper** [comment]
np! Be glad to hear it! Google has some ideas it looks like, but some assume Apache or add other tech in place it looks like (but I took only a cursory look!)
