### ISSUE TITLE
Moving to production images

### ISSUE THREAD

**Issue by theobouwman** [shipping-docker/vessel#139]
## Description
How can I go from a dev env with Vessel to a ready to go production image?

**Comment by fideloper** [comment]
Hi!

This question is a bit bigger than I have time to answer, but the general answer is outlined in the shippingdocker.com course.

Of course, that's a paid course, which you may not be looking for. But the point is, it's a Big Topic™.


The general answer is:

1. Build a container for your app (you can take most of what Vessel does, ignoring things that attempt to generalize for Mac vs Linux vs Windows, and excluding stuff like xDebug)
2. Create a process that, when you push a tag/certain branch/whatever you want to trigger a deployment, builds a new Docker image with the code built into it
3. Upload that built container to a container registry (docker hub, aws ECR, or whatever works for you)
4. Use that container and deploy it <somewhere that supports containers> (your own server, an AWS service such as ECS / EKS  / fargate, Google cloud, azure, whatever you want!)

I do recommend the course I mentioned there because it really goes into the details about the "hard parts" of the above topics (there's not necessarily anything super hard, but there are plenty of details glossed over there).

(Also check out Udemy and other places to see what courses might work there too if you're looking to find guides on this!)

Hope this helps!

**Comment by theobouwman** [comment]
THanks for your response
