### ISSUE TITLE
How to set MySQL root password

### ISSUE THREAD

**Issue by mikeerickson** [shipping-docker/vessel#146]
## Description

I am trying to figure out how to set the MySQL root password when creating a new project. No matter how I set things, the root pow is always blank.  I have set the value in `docker-compose.yml` and have tried various settings in the project `.env`

I have scoured the docs and can’t seem to find anything?

## OS

My OS is:

- [x ] MacOS [Mojave]
- [x ] Linux

**Comment by fideloper** [comment]
Hi! It will use the password set by DB_PASSWORD env var but only sets the
password the first time the container is created (when mysql bootstraps
itself). After that it keeps the first settings.

You can reset that mysql container  (this erases any data in it!!) by
running “./vessel down -v” and then restarting it: “./vessel start”

However also check the docker-compose.yml file to make sure i’m right - it
has the setting   in the “mysql” environment setting and will tell you for
certain what env var it used to set that root password (and what other user
is created as well, since it creates a secondary user also).

They key point here is once the mysql container is created, the usernames
and passwords are set. Changing the env var doesn’t change the password any
longer.

**Comment by mikeerickson** [comment]
Hey @fideloper 

Ya, that is what I have set in `.env` but it doesn’t seem to use it when creating the MySQL container (this is what has me baffled) 

I have the default `docker-compose.yml` and the 

```yml
...
environment:
  MYSQL_ROOT__PASSWORD: “${DB_PASSWORD}”
...
```

and in `.env`

DB_PASSWORD=“test”

**Comment by mikeerickson** [comment]
If I call `./vessel stop` then change the password in `.env` to blank, then start again, I am able to successfully connect using `./vessel mysql`
