### ISSUE TITLE
Add second database to MySQL

### ISSUE THREAD

**Issue by craigward** [shipping-docker/vessel#69]
Hi, 

I'm loving Vessel but I'm having issues adding a second database to MySQL when it gets built. Whats the best way to do that?

Thanks

**Comment by mfour-merickson** [comment]
@craigward This can be done very easily manually.   Is this something you need to do on a very regular basis.

**Comment by craigward** [comment]
If I try to add one in Sequel Pro, I get an access denied error. But ideally, I want it to create a secondary database in its build. I couldn't figure out where to put the logic.

**Comment by craigward** [comment]
I've tried that, I log into Sequel Pro using the credentials in the .env file but I still can't create a new DB. 

I just get 

````
Couldn't create database.
MySQL said: Access denied for user 'docker'@'%' to database 'testing'
````

In my env file I have (and haven't changed it since they spun up)

````
DB_USERNAME=docker
DB_PASSWORD=secret
````

Ideally, I would like to have the database created when I first create the everything. The reason I am doing this is I have found issues using SQLite for testing.

**Comment by fideloper** [comment]
Well, user `docker` is not user `root`, so that makes sense. MySQL will set the password for user `root` as the same as your user `docker` by convention in Vessel's setup.

User user `root`, password `secret` when connecting to sequel pro.

(The privileges given to your user aren't a Vessel thing, but set by the mysql container's maintainers.)
 
**On creating multiple databases:** 

Vessel is basically "just" following the conventions set my the [mysql official container](https://hub.docker.com/_/mysql/), so you can see how to create extra databases when the mysql container is first created by following their docs. 

Specifically (I'm not sure its documented anymore?), the mysql container will run files ending in `.sh`, `.sql`, or `.sql.sh` if shared to the container's [`/docker-entrypoint-initdb.d/` directory](https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh#L176).

**Comment by craigward** [comment]
Perfect, Thanks @fideloper :)
